version: '3'
services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=anvesh
    restart: always
    ports:
      - 3306:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  flyway:
    image: flyway/flyway
    depends_on:
      - db
    command: -url=jdbc:mysql://db -schemas=myschema -user=root -password=anvesh -connectRetries=60 migrate
    tty: true
    volumes:
      - /root/flyway/my/sqldir:/flyway/sql
	  -./:/flyway/conf
	  -./:/flyway/jars
	  -./:/flyway/drivers
    restart: always
	
	
#docker run --rm -v /root/flyname/my/sqldir:/flyway/sql flyway/flyway -url=jdbc:mysql://hostname/dbname -schemas=myschema -user=root -password=anvesh (info,migrate,validate,baseline)
#this is for mysql
